title: CoRE-Math
description: Africa–Europe collaboration in the mathematical sciences

baseurl: "/-core-math-website-test"
url: "https://bengtove.github.io"

permalink: /news/:year/:title/

collections:
  programmes:
    output: true
    permalink: /programmes/:name/
  projects:
    output: true
    permalink: /projects/:name/
  research_groups:
    output: true
    permalink: /research-groups/:name/
  events:
    output: true
    permalink: /events/:name/
  publications:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "events"
    values:
      layout: event
  - scope:
      path: ""
    values:
      layout: default
